using SkyrimJPStringPatcher.Core;

namespace SkyrimJPStringPatcher.Tests.Core;

/// <summary>Uses checked-in fixture files under Fixtures/ (copied next to the
/// test binary at build time) instead of generating test data at runtime — a
/// fixture's content is inspectable directly (open the .tsv, see exactly what
/// is being tested) and stays fixed unless someone deliberately edits it (a
/// git diff on the fixture itself then shows the intent), which is what makes
/// this a meaningful regression test rather than a self-referential one where
/// the "expected" data is generated by the same code being tested.</summary>
public class CandidateIoTests
{
    private static string FixturePath(string name) => Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    private static readonly Candidate FullFormatCandidate = new(
        WinningPlugin: "Skyrim.esm",
        FormId: "00012345",
        RecordType: "PERK FULL",
        CurrentText: "Some\tText\nWith Escapes",
        Index: 2,
        EditorId: "SomeEditorId",
        Context: "Some Context",
        StaleOriginal: "Old Text",
        StaleTranslation: "古いテキスト",
        Warning: "PickUpTargetClassificationFailed",
        CrossModPrecedentJapanese: "過去の訳文",
        CrossModPrecedentNeedsReview: true);

    [Fact]
    public void ReadTsv_FullFormatFixture_ParsesEveryFieldCorrectly()
    {
        var result = CandidateIo.ReadTsv(FixturePath("candidate_full_format.tsv"));

        var c = Assert.Single(result);
        Assert.Equal(FullFormatCandidate, c);
    }

    [Fact]
    public void WriteTsv_MatchesCheckedInGoldenFile()
    {
        // Regression check on the serialized FORMAT itself: if WriteTsv's column
        // order/escaping ever changes, this fails with a direct line-by-line
        // diff against Fixtures/candidate_full_format.tsv instead of just
        // "some assertion failed".
        var path = Path.GetTempFileName();
        try
        {
            CandidateIo.WriteTsv(path, new[] { FullFormatCandidate });

            var actualLines = File.ReadAllLines(path);
            var expectedLines = File.ReadAllLines(FixturePath("candidate_full_format.tsv"));
            Assert.Equal(expectedLines, actualLines);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ReadTsv_ToleratesOldRowsWithoutTrailingColumns()
    {
        // v0.54.2 (known issue 21) added the "Warning" column at the end. A TSV
        // written by an older build won't have it — ReadTsv must not throw, and
        // must default the missing fields to "".
        var result = CandidateIo.ReadTsv(FixturePath("old_format_no_warning_column.tsv"));

        var c = Assert.Single(result);
        Assert.Equal("00012345", c.FormId);
        Assert.Equal("Skyrim.esm", c.WinningPlugin);
        Assert.Equal("PERK FULL", c.RecordType);
        Assert.Equal("Some Text", c.CurrentText);
        Assert.Equal(0, c.Index);
        Assert.Equal("", c.EditorId);
        Assert.Equal("", c.Context);
        Assert.Equal("", c.StaleOriginal);
        Assert.Equal("", c.StaleTranslation);
        Assert.Equal("", c.Warning);
    }

    [Fact]
    public void ReadTsv_SkipsBlankLines()
    {
        var result = CandidateIo.ReadTsv(FixturePath("candidates_with_blank_line.tsv"));

        Assert.Single(result);
    }

    [Fact]
    public void ReadTsv_NonexistentPath_ThrowsFileNotFoundException()
    {
        var path = Path.Combine(Path.GetTempPath(), $"sjpts_tests_nonexistent_{Guid.NewGuid():N}.tsv");

        Assert.Throws<FileNotFoundException>(() => CandidateIo.ReadTsv(path));
    }
}
