using SkyrimJPStringPatcher.Core;

namespace SkyrimJPStringPatcher.Tests.Core;

/// <summary>Mirrors CandidateIoTests' golden-file approach for CorpusIo, the
/// sibling interchange-file reader/writer that previously had no dedicated
/// tests of its own. Covers the two behaviors CorpusIo documents as real,
/// measured decisions: exact-duplicate-row dedup on write (~24% of one real
/// corpus, 7,200/29,587 rows) and tolerating a pre-v0.5.0 file with no
/// DsdType column.</summary>
public class CorpusIoTests
{
    private static string FixturePath(string name) => Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    private static readonly CorpusEntry FullFormatEntry = new(
        English: "Some\tText\nWith Escapes",
        Japanese: "何か\tテキスト\n改行あり",
        Source: "Skyrim.esm",
        SourceKind: "vanilla",
        DsdType: "PERK FULL");

    [Fact]
    public void ReadTsv_FullFormatFixture_ParsesEveryFieldCorrectly()
    {
        var result = CorpusIo.ReadTsv(FixturePath("corpus_full_format.tsv"));

        var entry = Assert.Single(result);
        Assert.Equal(FullFormatEntry, entry);
    }

    [Fact]
    public void WriteTsv_MatchesCheckedInGoldenFile()
    {
        // Regression check on the serialized FORMAT itself: if WriteTsv's column
        // order/escaping ever changes, this fails with a direct line-by-line
        // diff against Fixtures/corpus_write_golden.tsv instead of just
        // "some assertion failed".
        var path = Path.GetTempFileName();
        try
        {
            CorpusIo.WriteTsv(path, new[] { FullFormatEntry });

            var actualLines = File.ReadAllLines(path);
            var expectedLines = File.ReadAllLines(FixturePath("corpus_write_golden.tsv"));
            Assert.Equal(expectedLines, actualLines);
        }
        finally
        {
            File.Delete(path);
        }
    }

    /// <summary>The real behavior this class exists to document: PickUpTarget's
    /// record-by-record collection legitimately adds the same (English,
    /// Japanese, Source, SourceKind, DsdType) row once per record that shares a
    /// common placeholder string — WriteTsv must collapse exact duplicates
    /// rather than writing every occurrence.</summary>
    [Fact]
    public void WriteTsv_ExactDuplicateRows_AreCollapsedToOne()
    {
        // Read from a checked-in fixture (not constructed in-memory) so the
        // duplicate-detection input isn't self-referentially generated by the
        // same test — mirrors how PickUpTarget's own raw, pre-dedup corpus
        // collection would actually look on disk.
        var rawEntries = CorpusIo.ReadTsv(FixturePath("corpus_with_duplicate_rows.tsv"));
        Assert.Equal(3, rawEntries.Count); // fixture has 2 identical rows + 1 distinct row

        var path = Path.GetTempFileName();
        try
        {
            CorpusIo.WriteTsv(path, rawEntries);

            var written = CorpusIo.ReadTsv(path);
            Assert.Equal(2, written.Count); // the exact-duplicate pair collapsed to 1
            Assert.Contains(written, e => e.English == "(Invisible Continue)");
            Assert.Contains(written, e => e.English == "Steel Sword");
        }
        finally
        {
            File.Delete(path);
        }
    }

    /// <summary>Rows with a DIFFERENT Source/SourceKind for the same English/
    /// Japanese pair are NOT the "exact duplicate" case (a separate provenance
    /// judgment call, deliberately out of scope) — dedup must only collapse
    /// rows where ALL FOUR columns match exactly.</summary>
    [Fact]
    public void WriteTsv_SamePairDifferentSource_IsNotCollapsed()
    {
        var entries = new List<CorpusEntry>
        {
            new("Steel Sword", "鋼の剣", "Skyrim.esm", "vanilla", "WEAP FULL"),
            new("Steel Sword", "鋼の剣", "SomeMod.esp", "dsd", "WEAP FULL"),
        };
        var path = Path.GetTempFileName();
        try
        {
            CorpusIo.WriteTsv(path, entries);

            var written = CorpusIo.ReadTsv(path);
            Assert.Equal(2, written.Count);
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ReadTsv_ToleratesOldRowsWithoutDsdTypeColumn()
    {
        var result = CorpusIo.ReadTsv(FixturePath("corpus_old_format_no_dsdtype_column.tsv"));

        var entry = Assert.Single(result);
        Assert.Equal("Old Format Entry", entry.English);
        Assert.Equal("旧形式エントリ", entry.Japanese);
        Assert.Equal("TestMod.esp", entry.Source);
        Assert.Equal("dsd", entry.SourceKind);
        Assert.Equal("", entry.DsdType);
    }

    [Fact]
    public void ReadTsv_SkipsBlankLines()
    {
        var result = CorpusIo.ReadTsv(FixturePath("corpus_with_blank_line.tsv"));

        Assert.Single(result);
    }

    [Fact]
    public void ReadTsv_SkipsRowsWithFewerThanFourColumns()
    {
        var result = CorpusIo.ReadTsv(FixturePath("corpus_with_too_few_columns.tsv"));

        var entry = Assert.Single(result);
        Assert.Equal("Steel Sword", entry.English);
    }

    [Fact]
    public void ReadTsv_NonexistentPath_ThrowsFileNotFoundException()
    {
        var path = Path.Combine(Path.GetTempPath(), $"sjpts_tests_nonexistent_{Guid.NewGuid():N}.tsv");

        Assert.Throws<FileNotFoundException>(() => CorpusIo.ReadTsv(path));
    }
}
